# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: booking.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='booking.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rbooking.proto\"\x15\n\x07MovieID\x12\n\n\x02id\x18\x01 \x01(\t\"\x0e\n\x0c\x42ookingEmpty\"\x1b\n\x0b\x42ookingDate\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\"?\n\x15\x42ookingDateAndMovieID\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x18\n\x10scheduled_movies\x18\x02 \x03(\t\"\x14\n\x06UserID\x12\n\n\x02id\x18\x01 \x01(\t\"<\n\x04\x42ook\x12\x0e\n\x06userid\x18\x01 \x01(\t\x12$\n\x04\x64\x61te\x18\x02 \x01(\x0b\x32\x16.BookingDateAndMovieID2\xb0\x01\n\x07\x42ooking\x12+\n\x0fGetListBookings\x12\r.BookingEmpty\x1a\x05.Book\"\x00\x30\x01\x12\x39\n\x0fGetMoviesByDate\x12\x0c.BookingDate\x1a\x16.BookingDateAndMovieID\"\x00\x12\"\n\x0cGetUsersBook\x12\x07.UserID\x1a\x05.Book\"\x00\x30\x01\x12\x19\n\x07\x41\x64\x64\x42ook\x12\x05.Book\x1a\x05.Book\"\x00\x62\x06proto3'
)




_MOVIEID = _descriptor.Descriptor(
  name='MovieID',
  full_name='MovieID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='MovieID.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=38,
)


_BOOKINGEMPTY = _descriptor.Descriptor(
  name='BookingEmpty',
  full_name='BookingEmpty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=54,
)


_BOOKINGDATE = _descriptor.Descriptor(
  name='BookingDate',
  full_name='BookingDate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='date', full_name='BookingDate.date', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=83,
)


_BOOKINGDATEANDMOVIEID = _descriptor.Descriptor(
  name='BookingDateAndMovieID',
  full_name='BookingDateAndMovieID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='date', full_name='BookingDateAndMovieID.date', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='scheduled_movies', full_name='BookingDateAndMovieID.scheduled_movies', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=148,
)


_USERID = _descriptor.Descriptor(
  name='UserID',
  full_name='UserID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='UserID.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=150,
  serialized_end=170,
)


_BOOK = _descriptor.Descriptor(
  name='Book',
  full_name='Book',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='userid', full_name='Book.userid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='date', full_name='Book.date', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=172,
  serialized_end=232,
)

_BOOK.fields_by_name['date'].message_type = _BOOKINGDATEANDMOVIEID
DESCRIPTOR.message_types_by_name['MovieID'] = _MOVIEID
DESCRIPTOR.message_types_by_name['BookingEmpty'] = _BOOKINGEMPTY
DESCRIPTOR.message_types_by_name['BookingDate'] = _BOOKINGDATE
DESCRIPTOR.message_types_by_name['BookingDateAndMovieID'] = _BOOKINGDATEANDMOVIEID
DESCRIPTOR.message_types_by_name['UserID'] = _USERID
DESCRIPTOR.message_types_by_name['Book'] = _BOOK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MovieID = _reflection.GeneratedProtocolMessageType('MovieID', (_message.Message,), {
  'DESCRIPTOR' : _MOVIEID,
  '__module__' : 'booking_pb2'
  # @@protoc_insertion_point(class_scope:MovieID)
  })
_sym_db.RegisterMessage(MovieID)

BookingEmpty = _reflection.GeneratedProtocolMessageType('BookingEmpty', (_message.Message,), {
  'DESCRIPTOR' : _BOOKINGEMPTY,
  '__module__' : 'booking_pb2'
  # @@protoc_insertion_point(class_scope:BookingEmpty)
  })
_sym_db.RegisterMessage(BookingEmpty)

BookingDate = _reflection.GeneratedProtocolMessageType('BookingDate', (_message.Message,), {
  'DESCRIPTOR' : _BOOKINGDATE,
  '__module__' : 'booking_pb2'
  # @@protoc_insertion_point(class_scope:BookingDate)
  })
_sym_db.RegisterMessage(BookingDate)

BookingDateAndMovieID = _reflection.GeneratedProtocolMessageType('BookingDateAndMovieID', (_message.Message,), {
  'DESCRIPTOR' : _BOOKINGDATEANDMOVIEID,
  '__module__' : 'booking_pb2'
  # @@protoc_insertion_point(class_scope:BookingDateAndMovieID)
  })
_sym_db.RegisterMessage(BookingDateAndMovieID)

UserID = _reflection.GeneratedProtocolMessageType('UserID', (_message.Message,), {
  'DESCRIPTOR' : _USERID,
  '__module__' : 'booking_pb2'
  # @@protoc_insertion_point(class_scope:UserID)
  })
_sym_db.RegisterMessage(UserID)

Book = _reflection.GeneratedProtocolMessageType('Book', (_message.Message,), {
  'DESCRIPTOR' : _BOOK,
  '__module__' : 'booking_pb2'
  # @@protoc_insertion_point(class_scope:Book)
  })
_sym_db.RegisterMessage(Book)



_BOOKING = _descriptor.ServiceDescriptor(
  name='Booking',
  full_name='Booking',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=235,
  serialized_end=411,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetListBookings',
    full_name='Booking.GetListBookings',
    index=0,
    containing_service=None,
    input_type=_BOOKINGEMPTY,
    output_type=_BOOK,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetMoviesByDate',
    full_name='Booking.GetMoviesByDate',
    index=1,
    containing_service=None,
    input_type=_BOOKINGDATE,
    output_type=_BOOKINGDATEANDMOVIEID,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetUsersBook',
    full_name='Booking.GetUsersBook',
    index=2,
    containing_service=None,
    input_type=_USERID,
    output_type=_BOOK,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='AddBook',
    full_name='Booking.AddBook',
    index=3,
    containing_service=None,
    input_type=_BOOK,
    output_type=_BOOK,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_BOOKING)

DESCRIPTOR.services_by_name['Booking'] = _BOOKING

# @@protoc_insertion_point(module_scope)
