# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import booking_pb2 as booking__pb2


class BookingStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetListBookings = channel.unary_stream(
                '/Booking/GetListBookings',
                request_serializer=booking__pb2.BookingEmpty.SerializeToString,
                response_deserializer=booking__pb2.Book.FromString,
                )
        self.GetMoviesByDate = channel.unary_unary(
                '/Booking/GetMoviesByDate',
                request_serializer=booking__pb2.BookingDate.SerializeToString,
                response_deserializer=booking__pb2.BookingDateAndMovieID.FromString,
                )
        self.GetUsersBook = channel.unary_stream(
                '/Booking/GetUsersBook',
                request_serializer=booking__pb2.UserID.SerializeToString,
                response_deserializer=booking__pb2.Book.FromString,
                )
        self.AddBook = channel.unary_unary(
                '/Booking/AddBook',
                request_serializer=booking__pb2.Book.SerializeToString,
                response_deserializer=booking__pb2.Book.FromString,
                )


class BookingServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetListBookings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMoviesByDate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUsersBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddBook(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BookingServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetListBookings': grpc.unary_stream_rpc_method_handler(
                    servicer.GetListBookings,
                    request_deserializer=booking__pb2.BookingEmpty.FromString,
                    response_serializer=booking__pb2.Book.SerializeToString,
            ),
            'GetMoviesByDate': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMoviesByDate,
                    request_deserializer=booking__pb2.BookingDate.FromString,
                    response_serializer=booking__pb2.BookingDateAndMovieID.SerializeToString,
            ),
            'GetUsersBook': grpc.unary_stream_rpc_method_handler(
                    servicer.GetUsersBook,
                    request_deserializer=booking__pb2.UserID.FromString,
                    response_serializer=booking__pb2.Book.SerializeToString,
            ),
            'AddBook': grpc.unary_unary_rpc_method_handler(
                    servicer.AddBook,
                    request_deserializer=booking__pb2.Book.FromString,
                    response_serializer=booking__pb2.Book.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Booking', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Booking(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetListBookings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Booking/GetListBookings',
            booking__pb2.BookingEmpty.SerializeToString,
            booking__pb2.Book.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMoviesByDate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Booking/GetMoviesByDate',
            booking__pb2.BookingDate.SerializeToString,
            booking__pb2.BookingDateAndMovieID.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUsersBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Booking/GetUsersBook',
            booking__pb2.UserID.SerializeToString,
            booking__pb2.Book.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddBook(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Booking/AddBook',
            booking__pb2.Book.SerializeToString,
            booking__pb2.Book.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
